encryption/Controllers/CaesarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text.RegularExpressions;

namespace encryption.Controllers
{
    public class CaesarController : Controller
    {
        //Encryption Action
        public IActionResult CaesarEncryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CaesarEncryption(string plainText, int key)
        {

            if (key >= 0)
            {
                ViewBag.Massage = CaesarEncrypt(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid! The key must be a positive number";

            return View();
        }

        //Decryption Action

        public IActionResult CaesarDecryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CaesarDecryption(string ciphertext, int key)
        {
            if (key >= 0)
            {
                ViewBag.Massage = CaesarDecrypt(ciphertext, key);

            }
            else
                ViewBag.Massage = "Invalid! The key must be a positive number";

            return View();
        }


        //Caesar Cipher Algorithm

        public static string CaesarEncrypt(string plaintext, int key)
        {
            // Remove any non-letter characters from the plaintext and convert to uppercase
            plaintext = Regex.Replace(plaintext, "[^A-Za-z]+", "").ToUpper();

            string ciphertext = "";
            foreach (char c in plaintext)
            {
                char encryptedChar = (char)((((int)c - 'A' + key) % 26) + 'A');
                ciphertext += encryptedChar;
            }
            return ciphertext;
        }

        public static string CaesarDecrypt(string ciphertext, int key)
        {
            // Remove any non-letter characters from the plaintext and convert to uppercase
            ciphertext = Regex.Replace(ciphertext, "[^A-Za-z]+", "").ToUpper();

            string plaintext = "";
            foreach (char c in ciphertext)
            {
                char decryptedChar = (char)((((int)c - 'A' - key + 26) % 26) + 'A');
                plaintext += decryptedChar;
            }
            return plaintext;
        }
    }
}

encryption/Controllers/SecurityController.cs
using encryption.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text;

namespace encryption.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Encryption()
        {
            return View();
        }

        public IActionResult Decryption()
        {
            return View();
        }


        // Monoalphabetic Action
        //Encryption Action
        public IActionResult MonoalphabeticEncryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult MonoalphabeticEncryption(string plainText, string key)
        {
            if (!String.IsNullOrEmpty(plainText))
            {
                ViewBag.Massage = MonoalphabeticEncrypt(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid";

            return View();
        }

        //Decryption Action
        public IActionResult MonoalphabeticDecryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult MonoalphabeticDecryption(string plainText, string key)
        {
            if (!String.IsNullOrEmpty(plainText))
            {
                ViewBag.Massage = MonoalphabeticDecrypt(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid";

            return View();
        }

        // Playfair Action
        //Encryption Action
        public IActionResult PlayfairEncryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PlayfairEncryption(string plainText, string key)
        {
            if (!String.IsNullOrEmpty(plainText))
            {
                ViewBag.Massage = PlayfairEncrypt(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid";

            return View();
        }

        //Decryption Action
        public IActionResult PlayfairDecryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PlayfairDecryption(string plainText, string key)
        {
            if (!String.IsNullOrEmpty(plainText))
            {
                ViewBag.Massage = PlayfairDecrypt(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid";

            return View();
        }

        // HillCipher Action
        //Encryption Action
        public IActionResult HillCipherEncryption()
        {
            return View();
        }

        [HttpPost]
        public IActionResult HillCipherEncryption(string plainText, string key)
        {
            if (!String.IsNullOrEmpty(plainText))
            {
                ViewBag.Massage = HillCipher(plainText, key);

            }
            else
                ViewBag.Massage = "Invalid";

            return View();
        }

        //------------------------------------------------------        

        // Monoalphabetic Cipher Algorithm
        static string MonoalphabeticEncrypt(string plainText, string key)
        {
            char[] chars = new char[plainText.Length];
            for (int i = 0; i < plainText.Length; i++)
            {
                if (plainText[i] == ' ')
                {
                    chars[i] = ' ';
                }

                else
                {
                    int j = plainText[i] - 97;
                    chars[i] = key[j];
                }
            }

            return new string(chars);
        }

        static string MonoalphabeticDecrypt(string cipherText, string key)
        {
            char[] chars = new char[cipherText.Length];
            for (int i = 0; i < cipherText.Length; i++)
            {
                if (cipherText[i] == ' ')
                {
                    chars[i] = ' ';
                }
                else
                {
                    int j = key.IndexOf(cipherText[i]) + 97;
                    chars[i] = (char)j;
                }
            }
            return new string(chars);
        }
        //Playfair Cipher Algorithm
        private static int PlayfairMod(int a, int b)
        {
            return (a % b + b) % b;
        }

        private static List<int> PlayfairFindAllOccurrences(string str, char value)
        {
            List<int> indexes = new List<int>();

            int index = 0;
            while ((index = str.IndexOf(value, index)) != -1)
                indexes.Add(index++);

            return indexes;
        }

        private static string PlayfairRemoveAllDuplicates(string str, List<int> indexes)
        {
            string retVal = str;

            for (int i = indexes.Count - 1; i >= 1; i--)
                retVal = retVal.Remove(indexes[i], 1);

            return retVal;
        }

        private static char[,] PlayfairGenerateKeySquare(string key)
        {
            char[,] keySquare = new char[5, 5];
            string defaultKeySquare = "ABCDEFGHIKLMNOPQRSTUVWXYZ";
            string tempKey = string.IsNullOrEmpty(key) ? "CIPHER" : key.ToUpper();

            tempKey = tempKey.Replace("J", "");
            tempKey += defaultKeySquare;

            for (int i = 0; i < 25; ++i)
            {
                List<int> indexes = PlayfairFindAllOccurrences(tempKey, defaultKeySquare[i]);
                tempKey = PlayfairRemoveAllDuplicates(tempKey, indexes);
            }

            tempKey = tempKey.Substring(0, 25);

            for (int i = 0; i < 25; ++i)
                keySquare[(i / 5), (i % 5)] = tempKey[i];

            return keySquare;
        }

        private static void PlayfairGetPosition(ref char[,] keySquare, char ch, ref int row, ref int col)
        {
            if (ch == 'J')
                PlayfairGetPosition(ref keySquare, 'I', ref row, ref col);

            for (int i = 0; i < 5; ++i)
                for (int j = 0; j < 5; ++j)
                    if (keySquare[i, j] == ch)
                    {
                        row = i;
                        col = j;
                    }
        }

        private static char[] PlayfairSameRow(ref char[,] keySquare, int row, int col1, int col2, int encipher)
        {
            return new char[] { keySquare[row, PlayfairMod((col1 + encipher), 5)], keySquare[row, PlayfairMod((col2 + encipher), 5)] };
        }

        private static char[] PlayfairSameColumn(ref char[,] keySquare, int col, int row1, int row2, int encipher)
        {
            return new char[] { keySquare[PlayfairMod((row1 + encipher), 5), col], keySquare[PlayfairMod((row2 + encipher), 5), col] };
        }

        private static char[] PlayfairSameRowColumn(ref char[,] keySquare, int row, int col, int encipher)
        {
            return new char[] { keySquare[PlayfairMod((row + encipher), 5), PlayfairMod((col + encipher), 5)], keySquare[PlayfairMod((row + encipher), 5), PlayfairMod((col + encipher), 5)] };
        }

        private static char[] PlayfairDifferentRowColumn(ref char[,] keySquare, int row1, int col1, int row2, int col2)
        {
            return new char[] { keySquare[row1, col2], keySquare[row2, col1] };
        }

        private static string PlayfairRemoveOtherChars(string input)
        {
            string output = input;

            for (int i = 0; i < output.Length; ++i)
                if (!char.IsLetter(output[i]))
                    output = output.Remove(i, 1);

            return output;
        }

        private static string PlayfairAdjustOutput(string input, string output)
        {
            StringBuilder retVal = new StringBuilder(output);

            for (int i = 0; i < input.Length; ++i)
            {
                if (!char.IsLetter(input[i]))
                    retVal = retVal.Insert(i, input[i].ToString());

                if (char.IsLower(input[i]))
                    retVal[i] = char.ToLower(retVal[i]);
            }

            return retVal.ToString();
        }

        private static string Playfair(string input, string key, bool encipher)
        {
            string retVal = string.Empty;
            char[,] keySquare = PlayfairGenerateKeySquare(key);
            string tempInput = PlayfairRemoveOtherChars(input);
            int e = encipher ? 1 : -1;

            if ((tempInput.Length % 2) != 0)
                tempInput += "X";

            for (int i = 0; i < tempInput.Length; i += 2)
            {
                int row1 = 0;
                int col1 = 0;
                int row2 = 0;
                int col2 = 0;

                PlayfairGetPosition(ref keySquare, char.ToUpper(tempInput[i]), ref row1, ref col1);
                PlayfairGetPosition(ref keySquare, char.ToUpper(tempInput[i + 1]), ref row2, ref col2);

                if (row1 == row2 && col1 == col2)
                {
                    retVal += new string(PlayfairSameRowColumn(ref keySquare, row1, col1, e));
                }
                else if (row1 == row2)
                {
                    retVal += new string(PlayfairSameRow(ref keySquare, row1, col1, col2, e));
                }
                else if (col1 == col2)
                {
                    retVal += new string(PlayfairSameColumn(ref keySquare, col1, row1, row2, e));
                }
                else
                {
                    retVal += new string(PlayfairDifferentRowColumn(ref keySquare, row1, col1, row2, col2));
                }
            }

            retVal = PlayfairAdjustOutput(input, retVal);

            return retVal;
        }

        public static string PlayfairEncrypt(string input, string key)
        {
            return Playfair(input, key, true);
        }

        public static string PlayfairDecrypt(string input, string key)
        {
            return Playfair(input, key, false);
        }

        //Hill Cipher Algorithm
        public static void HillCiphergetKeyMatrix(String key,

encryption/Views/Security/Decryption.cshtml
<html>
<head>
    <title>Decryption</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* CSS styles for the page */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        h1 {
            text-align: center;
            margin-top: 50px;
        }

        .list {
            margin: 50px auto;
            max-width: 800px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            overflow: hidden;
        }

            .list ul {
                list-style: none;
                margin: 0;
                padding: 0;
            }

            .list li {
                border-bottom: 1px solid #ccc;
                padding: 10px 0;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }

                .list li:last-child {
                    border-bottom: none;
                }

                .list li .title {
                    font-size: 18px;
                    font-weight: bold;
                    color: #333;
                    margin-right: 20px;
                }

                .list li .description {
                    font-size: 16px;
                    color: #666;
                    margin-right: auto;
                }

                .list li .actions {
                    display: flex;
                    align-items: center;
                }

                    .list li .actions a {
                        display: inline-block;
                        padding: 5px 10px;
                        background-color: #007bff;
                        color: #fff;
                        text-decoration: none;
                        border-radius: 5px;
                        margin-right: 10px;
                        transition: background-color 0.3s ease;
                    }

                        .list li .actions a:hover {
                            background-color: #0062cc;
                        }

                    .list li .actions button {
                        display: inline-block;
                        padding: 5px 10px;
                        background-color: #dc3545;
                        color: #fff;
                        text-decoration: none;
                        border-radius: 5px;
                        margin-right: 10px;
                        transition: background-color 0.3s ease;
                        border: none;
                        cursor: pointer;
                    }

                        .list li .actions button:hover {
                            background-color: #c82333;
                        }

                        .list li .actions button:active {
                            transform: translateY(1px);
                        }
    </style>

</head>
<body>
    <h1>Decryption Algorithms</h1>
    <div class="list">
        <ul>
            <li>
                <div class="title">Caesar Cipher</div>
                <div class="description">The encryption process using the Caesar cipher is straightforward.</div>
                <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="CaesarDecryption">Decrypt</a>
                </div>
            </li>
            <li>
                <div class="title">Monoalphabetic</div>
                <div class="description">This is the description for item 2.</div>
                <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="MonoalphabeticDecryption">Decrypt</a>
                </div>
            </li>
            <li>
                <div class="title">Playfair</div>
                <div class="description">This is the description for item 3.</div>
                <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="PlayfairDecryption">Decrypt</a>
                </div>
            </li>
        </ul>
    </div>
</body>
</html>

encryption/Views/Security/Encryption.cshtml
<html>
  <head>
    <title>Encryption</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      /* CSS styles for the page */
      body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
      }
      h1 {
        text-align: center;
        margin-top: 50px;
      }
      .list {
        margin: 50px auto;
        max-width: 800px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        overflow: hidden;
      }
      .list ul {
        list-style: none;
        margin: 0;
        padding: 0;
      }
      .list li {
        border-bottom: 1px solid #ccc;
        padding: 10px 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .list li:last-child {
        border-bottom: none;
      }
      .list li .title {
        font-size: 18px;
        font-weight: bold;
        color: #333;
        margin-right: 20px;
      }
      .list li .description {
        font-size: 16px;
        color: #666;
        margin-right: auto;
      }
      .list li .actions {
        display: flex;
        align-items: center;
      }
      .list li .actions a {
        display: inline-block;
        padding: 5px 10px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        margin-right: 10px;
        transition: background-color 0.3s ease;
      }
      .list li .actions a:hover {
        background-color: #0062cc;
      }
      .list li .actions button {
        display: inline-block;
        padding: 5px 10px;
        background-color: #dc3545;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        margin-right: 10px;
        transition: background-color 0.3s ease;
        border: none;
        cursor: pointer;
      }
      .list li .actions button:hover {
        background-color: #c82333;
      }
      .list li .actions button:active {
        transform: translateY(1px);
      }
    </style>

  </head>
  <body>
    <h1>Encryption Algorithms</h1>
    <div class="list">
      <ul>
        <li>
                <div class="title">Caesar Cipher</div>
                <div class="description">The encryption process using the Caesar cipher is straightforward.</div>
                <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Caesar" asp-action="CaesarEncryption">Encrypt</a>
          </div>
        </li>
        <li>
                <div class="title">Monoalphabetic</div>
          <div class="description">This is the description for item 2.</div>
          <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="MonoalphabeticEncryption">Encrypt</a>
          </div>
        </li>
        <li>
                <div class="title">Playfair</div>
          <div class="description">This is the description for item 3.</div>
          <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="PlayfairEncryption">Encrypt</a>
          </div>
        </li>
        <li>
                <div class="title">Hill Cipher</div>
          <div class="description">This is the description for item 4.</div>
          <div class="actions">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="HillCipherEncryption">Encrypt</a>
          </div>
        </li>
      </ul>
    </div>
  </body>
</html>

encryption/Views/Security/HillCipherEncryption.cshtml
<html>
    <head>

    </head>

    <body>

        <h2>Hill Cipher</h2>

        <form method="post">

            <div class="form-group">
                <input type="text" class="form-control" id="plainText" name="plainText" placeholder="String: " style="width: 50%" />
            </div>
            <br />

            <div class="form-group">
                <input type="number" class="form-control" id="key" name="key" placeholder = "Key: " style = "width: 50%"/>
            </div>
            <br />

        <button class="btn btn-primary" type="submit">Encrypt</button>
        </form>
        <br />

        <div class="form-control" style="width: 50%">
            <label>Encryption: </label>
            @ViewBag.Massage
        </div>

        <a class="btn btn-primary" asp-area="" asp-controller="Security" asp-action="Encryption" style="margin-top: 10%; margin-left:50%;">Back</a>

    </body>
</html>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

encryption/Views/Security/MonoalphabeticDecryption.cshtml
<html>
    <head>

    </head>

    <body>

        <h2>Monoalphabetic Cipher</h2>

        <form method="post">

            <div class="form-group">
            <input type="text" class="form-control" id="plainText" name="plainText" placeholder="String: " style="width: 50%"/>
            </div>
            <br />

            <div class="form-group">
                <input type="number" class="form-control" id="Key" name="Key" placeholder="Key: " style="width: 50%" />
            </div>
            <br />

            <button class="btn btn-primary" type="submit">Decrypt</button>

        </form>
        <br />

        <div class="form-control" style="width: 50%">
            <label>Decryption: </label>
            @ViewBag.Massage
        </div>

        <a class="btn btn-primary" asp-area="" asp-controller="Security" asp-action="Decryption" style="margin-top: 10%; margin-left:50%;">Back</a>

    </body>
</html>

encryption/Views/Security/PlayfairDecryption.cshtml
<html>
<head>

</head>

<body>

    <h2>Playfair Cipher</h2>

    <form method="post">

        <div class="form-group">
            <input type="text" class="form-control" id="plainText" name="plainText" placeholder="String: " style="width: 50%"/>
        </div>
        <br />

        <div class="form-group">
            <input type="number" class="form-control" id="Key" name="Key" placeholder="Key: " style="width: 50%" />
        </div>
        <br />

        <button class="btn btn-primary" type="submit">Decrypt</button>

    </form>
    <br />

    <div class="form-control" style="width: 50%">
        <label>Decryption: </label>
        @ViewBag.Massage
    </div>

    <a class="btn btn-primary" asp-area="" asp-controller="Security" asp-action="Decryption" style="margin-top: 10%; margin-left:50%;">Back</a>

</body>
</html>

encryption/Views/Security/PlayfairEncryption.cshtml
<html>
    <head>

    </head>

    <body>

        <h2>Playfair Cipher</h2>

        <form method="post">

            <div class="form-group">
                <input type="text" class="form-control" id="plainText" name="plainText" placeholder="String: " style="width: 50%" />
            </div>
            <br />

            <div class="form-group">
                <input type="number" class="form-control" id="key" name="key" placeholder = "Key: " style = "width: 50%"/>
            </div>
            <br />

            <button class="btn btn-primary" type="submit">Encrypt</button>

        </form>
        <br />

        <div class="form-control" style="width: 50%">
            <label>Encryption: </label>
            @ViewBag.Massage
        </div>

        <a class="btn btn-primary" asp-area="" asp-controller="Security" asp-action="Encryption" style="margin-top: 10%; margin-left:50%;">Back</a>

    </body>
</html>